"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import { Container } from '@mui/material'
import { createContext, useState } from 'react'
import Navbar from '@/components/Navbar'
import { SessionProvider } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const CartContext = createContext();

export default function RootLayout({ children }) {

  const [cart, setCart] = useState([]);

  return (
    <html lang="en">
      <body>
      <SessionProvider>
        
        <CartContext.Provider value={{cart,setCart}}>
          <Navbar/>
          <Container>
            {children}
          </Container>
        </CartContext.Provider>

      </SessionProvider>
        
        
      </body>
    </html>
  )
}

export {CartContext};
