"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import { Container } from '@mui/material'
import { createContext, useState } from 'react'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const CartContext = createContext();
const UserContext = createContext();

export default function RootLayout({ children }) {

  const [cart, setCart] = useState([]);
  const [authdata, setAuthdata] = useState(null);

  return (
    <html lang="en">
      <body>
      <UserContext.Provider value={{ authdata, setAuthdata }}>
        <CartContext.Provider value={{cart,setCart}}>
          <Navbar/>
          <Container>
            {children}
          </Container>
        </CartContext.Provider>
      </UserContext.Provider>

        
        
      </body>
    </html>
  )
}

export {UserContext,CartContext};
